# Generated by Django 5.0.6 on 2024-12-05 05:16

import Attendancesheet.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('zone', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=10, unique=True, validators=[Attendancesheet.models.validate_employee_code])),
                ('employee_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_work', models.DateField()),
                ('zone', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=10, validators=[Attendancesheet.models.validate_employee_code])),
                ('employee_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(default='NA', max_length=100)),
                ('shift', models.CharField(default='NA', max_length=10)),
                ('sk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sk_ot', models.IntegerField(default=0)),
                ('ssk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ssk_ot', models.IntegerField(default=0)),
                ('usk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('usk_ot', models.IntegerField(default=0)),
                ('attendance', models.BooleanField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobSetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('zone', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('low_stub', models.PositiveIntegerField(default=0)),
                ('anode_covering', models.PositiveIntegerField(default=0)),
                ('side_making', models.PositiveIntegerField(default=0)),
                ('hole', models.PositiveIntegerField(default=0)),
                ('house_keeping', models.PositiveIntegerField(default=0)),
                ('supply', models.PositiveIntegerField(default=0)),
                ('skilled', models.PositiveIntegerField(default=0)),
                ('semi_skilled', models.PositiveIntegerField(default=0)),
                ('unskilled', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='user', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
