# Generated by Django 5.1.6 on 2025-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendancesheet', '0002_alter_employeeattendance_sk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsetdetails',
            name='shift',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
